platform :ios, '10.3'
use_frameworks!

target 'provide_Example' do
  pod 'provide', :path => '../'
  pod 'KTSwiftExtensions', :path => '../../KTSwiftExtensions/'

  target 'provide_Tests' do
    inherit! :search_paths

    
  end
end
